defaults: &defaults
  feature_authentication: true
  feature_payment: true        
  feature_sign_in: false

development: 
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults

demo:
  <<: *defaults

production:
  <<: *defaults
  feature_authentication: false 
  feature_sign_in: true
