defaults: &defaults
  feature_login: true
  feature_payment: true
  feature_terms: true

development: 
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults

demo:
  <<: *defaults

production:
  <<: *defaults
  feature_login: false
  feature_terms: false
  
  