#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: goalnect
#  stack: bamboo-ree-1.8.7
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-33640820-1" 
    RAILS_ENV: "production"
    RACK_ENV: "production"
    GMAIL_USERNAME: "team@goalnect.com"
    GMAIL_PASSWORD: "helpmygoal1234"
    AWS_ACCESS_KEY_ID: 'AKIAJCALZQ2E4DOAZ4KA'
    AWS_SECRET_ACCESS_KEY: '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'
    AWS_S3_BUCKET: 'goalnect'
    FACEBOOK_APP_ID: '336745306400449'
    FACEBOOK_SECRET_KEY: '091732de83c8e3649e9c3a8f8f08f034'

staging:
  app: goalnect-staging
  stack: cedar
  config: &default
    BUNDLE_WITHOUT: "development:test"
    RAILS_ENV: "staging"
    RACK_ENV: "staging"
    GOOGLE_ANALYTICS: "UA-33640820-2" 
    GMAIL_USERNAME: "team@goalnect.com"
    GMAIL_PASSWORD: "helpmygoal1234"
    AWS_ACCESS_KEY_ID: 'AKIAJCALZQ2E4DOAZ4KA'
    AWS_SECRET_ACCESS_KEY: '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'
    AWS_S3_BUCKET: 'goalnectstaging'
    FACEBOOK_APP_ID: '476994358998838'
    FACEBOOK_SECRET_KEY: 'e53f9abc426980dbef7900b5b2c3a89e'
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard

demo: 
  app: goalnect-demo
  config: *default
  
