development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/goal_donation_payment_notifications/confirm"
  authenticity_token: DEVELOPMENTDEVELOPMENTDEVELOPMEN
  email: fabio@goalnect.com

test:
  <<: *development

staging:
  authenticity_token: 06AFDC23913D4942A20527527249ACC0
  email: camilahayashi@gmail.com
  return_to: "http://goalnect-staging.herokuapp.com/goal_donation_payment_notifications/confirm"

demo:
  <<: *development

production:
  authenticity_token: 14EFCD25D94742119FE117221330183F
  email: contato@goalnect.com
  return_to: "http://www.goalnect.com/goal_donation_payment_notifications/confirm"


  # https://ws.pagseguro.uol.com.br/v2/transactions?initialDate=2012-11-01T00:00&finalDate=2012-11-07T00:00&page=1&maxPageResults=100&email=camilahayashi@gmail.com&token=06AFDC23913D4942A20527527249ACC0