development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/goal_donation_payment_notifications/confirm"
  email: fabio@goalnect.com

test:
  <<: *development

staging:
  <<: *development
  base: "http://goalnect-staging.herokuapp.com"

demo:
  <<: *development

production:
  authenticity_token: 9CA8D46AF0C6177CB4C23D76CAF5E4B0
  email: user@example.com
  return_to: "http://exemplo.com.br/pedido/efetuado"
