development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/goal_donation_payment_notifications/confirm"
  authenticity_token: DEVELOPMENTDEVELOPMENTDEVELOPMEN
  email: fabio@goalnect.com

test:
  <<: *development

staging:
  authenticity_token: 06AFDC23913D4942A20527527249ACC0
  email: camilahayashi@gmail.com
  return_to: "http://goalnect-staging.herokuapp.com/goal_donation_payment_notifications/confirm"

demo:
  <<: *development

production:
  authenticity_token: 9CA8D46AF0C6177CB4C23D76CAF5E4B0
  email: user@example.com
  return_to: "http://exemplo.com.br/pedido/efetuado"
