require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoalDonationsController do

  # This should return the minimal set of attributes required to create a valid
  # GoalDonation. As you add validations to GoalDonation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoalDonationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all goal_donations as @goal_donations" do
      goal_donation = GoalDonation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:goal_donations).should eq([goal_donation])
    end
  end

  describe "GET show" do
    it "assigns the requested goal_donation as @goal_donation" do
      goal_donation = GoalDonation.create! valid_attributes
      get :show, {:id => goal_donation.to_param}, valid_session
      assigns(:goal_donation).should eq(goal_donation)
    end
  end

  describe "GET new" do
    it "assigns a new goal_donation as @goal_donation" do
      get :new, {}, valid_session
      assigns(:goal_donation).should be_a_new(GoalDonation)
    end
  end

  describe "GET edit" do
    it "assigns the requested goal_donation as @goal_donation" do
      goal_donation = GoalDonation.create! valid_attributes
      get :edit, {:id => goal_donation.to_param}, valid_session
      assigns(:goal_donation).should eq(goal_donation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GoalDonation" do
        expect {
          post :create, {:goal_donation => valid_attributes}, valid_session
        }.to change(GoalDonation, :count).by(1)
      end

      it "assigns a newly created goal_donation as @goal_donation" do
        post :create, {:goal_donation => valid_attributes}, valid_session
        assigns(:goal_donation).should be_a(GoalDonation)
        assigns(:goal_donation).should be_persisted
      end

      it "redirects to the created goal_donation" do
        post :create, {:goal_donation => valid_attributes}, valid_session
        response.should redirect_to(GoalDonation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved goal_donation as @goal_donation" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoalDonation.any_instance.stub(:save).and_return(false)
        post :create, {:goal_donation => {}}, valid_session
        assigns(:goal_donation).should be_a_new(GoalDonation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoalDonation.any_instance.stub(:save).and_return(false)
        post :create, {:goal_donation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested goal_donation" do
        goal_donation = GoalDonation.create! valid_attributes
        # Assuming there are no other goal_donations in the database, this
        # specifies that the GoalDonation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GoalDonation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => goal_donation.to_param, :goal_donation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested goal_donation as @goal_donation" do
        goal_donation = GoalDonation.create! valid_attributes
        put :update, {:id => goal_donation.to_param, :goal_donation => valid_attributes}, valid_session
        assigns(:goal_donation).should eq(goal_donation)
      end

      it "redirects to the goal_donation" do
        goal_donation = GoalDonation.create! valid_attributes
        put :update, {:id => goal_donation.to_param, :goal_donation => valid_attributes}, valid_session
        response.should redirect_to(goal_donation)
      end
    end

    describe "with invalid params" do
      it "assigns the goal_donation as @goal_donation" do
        goal_donation = GoalDonation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoalDonation.any_instance.stub(:save).and_return(false)
        put :update, {:id => goal_donation.to_param, :goal_donation => {}}, valid_session
        assigns(:goal_donation).should eq(goal_donation)
      end

      it "re-renders the 'edit' template" do
        goal_donation = GoalDonation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoalDonation.any_instance.stub(:save).and_return(false)
        put :update, {:id => goal_donation.to_param, :goal_donation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested goal_donation" do
      goal_donation = GoalDonation.create! valid_attributes
      expect {
        delete :destroy, {:id => goal_donation.to_param}, valid_session
      }.to change(GoalDonation, :count).by(-1)
    end

    it "redirects to the goal_donations list" do
      goal_donation = GoalDonation.create! valid_attributes
      delete :destroy, {:id => goal_donation.to_param}, valid_session
      response.should redirect_to(goal_donations_url)
    end
  end

end
