require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RedemptionPointTransactionsController do

  # This should return the minimal set of attributes required to create a valid
  # RedemptionPointTransaction. As you add validations to RedemptionPointTransaction, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RedemptionPointTransactionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all redemption_point_transactions as @redemption_point_transactions" do
      redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:redemption_point_transactions).should eq([redemption_point_transaction])
    end
  end

  describe "GET show" do
    it "assigns the requested redemption_point_transaction as @redemption_point_transaction" do
      redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
      get :show, {:id => redemption_point_transaction.to_param}, valid_session
      assigns(:redemption_point_transaction).should eq(redemption_point_transaction)
    end
  end

  describe "GET new" do
    it "assigns a new redemption_point_transaction as @redemption_point_transaction" do
      get :new, {}, valid_session
      assigns(:redemption_point_transaction).should be_a_new(RedemptionPointTransaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested redemption_point_transaction as @redemption_point_transaction" do
      redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
      get :edit, {:id => redemption_point_transaction.to_param}, valid_session
      assigns(:redemption_point_transaction).should eq(redemption_point_transaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RedemptionPointTransaction" do
        expect {
          post :create, {:redemption_point_transaction => valid_attributes}, valid_session
        }.to change(RedemptionPointTransaction, :count).by(1)
      end

      it "assigns a newly created redemption_point_transaction as @redemption_point_transaction" do
        post :create, {:redemption_point_transaction => valid_attributes}, valid_session
        assigns(:redemption_point_transaction).should be_a(RedemptionPointTransaction)
        assigns(:redemption_point_transaction).should be_persisted
      end

      it "redirects to the created redemption_point_transaction" do
        post :create, {:redemption_point_transaction => valid_attributes}, valid_session
        response.should redirect_to(RedemptionPointTransaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved redemption_point_transaction as @redemption_point_transaction" do
        # Trigger the behavior that occurs when invalid params are submitted
        RedemptionPointTransaction.any_instance.stub(:save).and_return(false)
        post :create, {:redemption_point_transaction => {}}, valid_session
        assigns(:redemption_point_transaction).should be_a_new(RedemptionPointTransaction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RedemptionPointTransaction.any_instance.stub(:save).and_return(false)
        post :create, {:redemption_point_transaction => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested redemption_point_transaction" do
        redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
        # Assuming there are no other redemption_point_transactions in the database, this
        # specifies that the RedemptionPointTransaction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RedemptionPointTransaction.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => redemption_point_transaction.to_param, :redemption_point_transaction => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested redemption_point_transaction as @redemption_point_transaction" do
        redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
        put :update, {:id => redemption_point_transaction.to_param, :redemption_point_transaction => valid_attributes}, valid_session
        assigns(:redemption_point_transaction).should eq(redemption_point_transaction)
      end

      it "redirects to the redemption_point_transaction" do
        redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
        put :update, {:id => redemption_point_transaction.to_param, :redemption_point_transaction => valid_attributes}, valid_session
        response.should redirect_to(redemption_point_transaction)
      end
    end

    describe "with invalid params" do
      it "assigns the redemption_point_transaction as @redemption_point_transaction" do
        redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RedemptionPointTransaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => redemption_point_transaction.to_param, :redemption_point_transaction => {}}, valid_session
        assigns(:redemption_point_transaction).should eq(redemption_point_transaction)
      end

      it "re-renders the 'edit' template" do
        redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RedemptionPointTransaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => redemption_point_transaction.to_param, :redemption_point_transaction => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested redemption_point_transaction" do
      redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
      expect {
        delete :destroy, {:id => redemption_point_transaction.to_param}, valid_session
      }.to change(RedemptionPointTransaction, :count).by(-1)
    end

    it "redirects to the redemption_point_transactions list" do
      redemption_point_transaction = RedemptionPointTransaction.create! valid_attributes
      delete :destroy, {:id => redemption_point_transaction.to_param}, valid_session
      response.should redirect_to(redemption_point_transactions_url)
    end
  end

end
